
#!/bin/zsh
#this script to send an amount of native token to multi wallets from a text file. token name can be bworks, lovelace (ada)
#zsh sendToMultiWallets.sh fromWallet tokenName amountToSend
#fromWallet: wallet that contains native token, tokenName: name of token to send, amountToSend: amount to send to each wallet
#./wallets.txt contains list of wallet address to receive token, each address is a new line. This file generated by js code with data from mongo.
#zsh sendToMultiWallets.sh wallet01 lovelace 1000000

source ./functions.sh

AMOUNT_TO_SEND=$3
TOKEN_NAME=$2
FROM_WALLET_NAME=$1

#select an utxo contains enough native token to send to all wallets
getInputTx ${FROM_WALLET_NAME}

let TX_OUTS
TX_OUT_PREFIX="--tx-out"
for line in "${(@f)"$(<./wallets.txt)"}"
{
  TX_OUTS=${TX_OUTS} ${TX_OUT_PREFIX}" ${line}+${AMOUNT_TO_SEND} ${TOKEN_NAME}"
}

echo ${TX_OUTS}

$CARDANO_CLI transaction build \
--babbage-era \
--tx-in ${SELECTED_UTXO} \
${TX_OUTS} \
--change-address 'addr_test1vz52h0cn9ua9vl8ak4yz4czas3sf3ftjy82a5tt7ladhufqyuk45c' \
--testnet-magic 1 \
--out-file tx.build


$CARDANO_CLI transaction sign \
--tx-body-file tx.build \
--signing-key-file ../wallets/${FROM_WALLET_NAME}.skey \
--out-file tx.signed

$CARDANO_CLI transaction submit --tx-file tx.signed --testnet-magic $TESTNET_MAGIC_NUM